### ISSUE TITLE
👑 Node Broker Delta Protocol

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb#11064]
**В рамках релиза 25-3 только включение ФФ**

## Description

Currently `Node Broker` sends out full node list information to all nodes when the epoch ends (usually every hour). This causes a periodic spike in network traffic. It is necessary to change the protocol to send out only node list changes (deltas).

Internal [design doc](https://github.com/ydb-platform/ydb-rfc/blob/main/node_broker_delta_protocol.md).

## Milestones

- [x] https://github.com/ydb-platform/ydb/issues/14134
- [x] https://github.com/ydb-platform/ydb/issues/15255
- [x] Support new delta protocol in `Node Broker` & `Dynamic Nameserver`
  - [x] https://github.com/ydb-platform/ydb/issues/15893
  - [x] https://github.com/ydb-platform/ydb/issues/15977
  - [x] https://github.com/ydb-platform/ydb/issues/15978
- [x] https://github.com/ydb-platform/ydb/issues/15979
- [x] https://github.com/ydb-platform/ydb/issues/17163
- [x] https://github.com/ydb-platform/ydb/pull/20982

## Improvements
- [x] #18790
- [x] https://github.com/ydb-platform/ydb/issues/20085
- [x] https://github.com/ydb-platform/ydb/issues/20696
- [ ] Intrusive containers for nodes on `Node Broker` side
