### ISSUE TITLE
👑 Local Incremental Backups

### ISSUE THREAD

**Issue by Enjection** [ydb-platform/ydb#11457]
## Description

Add intra-cluster incremental backups possibility and all infrastructure needed for further backup development as coherent feature.

Internal [design doc](https://github.com/ydb-platform/ydb-rfc/blob/main/0101_advanced-backups-rfc.md).

### Prerequisites

- [ ] Refactor SchemeShard to allow co-operations
- [ ] Refactor SchemeShard to allow cycles in operations
- [ ] Refactor SchemeShard to allow automatic required paths creation
- [ ] Add system columns support to schemeshard

### Main steps

- [ ] Add *Backup Collections* abstraction
- [ ] Add continuous backup operations
- [ ] Implement backup operation for `cluster` storage
- [ ] Implement incremental backup operation for `cluster` storage
- [ ] Implement restore operation for `cluster` storage
- [ ] Add SQL operations for all of the above
- [ ] Allow "old" backup/restore for backups saved in collection

**Comment by s-sabitova** [comment]
crit:
https://github.com/ydb-platform/ydb/issues/24389
https://github.com/ydb-platform/ydb/issues/24388

medium:
https://github.com/ydb-platform/ydb/issues/24386
https://github.com/ydb-platform/ydb/issues/24387
