### ISSUE TITLE
👑 Dynamic Nodes Autoscaling

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb#11456]
**В рамках релиза 25-3 только включение ФФ**

## Description

Users often provision more computing resources for their database than they need to handle peak load. It is necessary to add automatic change of the number of computing resources based on the load on a database.

Internal [design doc](https://github.com/ydb-platform/ydb-rfc/blob/main/autoscaling.md).

### Implementation
- [x] Add feature flag
- [x] Add gRPC API
- [x] Collect CPU utilization metric from dynamic nodes
- [x] Add target tracking algorithm implementation
- [x] Add configurable settings for target tracking algorithm
- [x] Add monitoring sensors
- [x] Enable feature flag by default

### Docs
- [x] Add documentation

### Issues
- [x] https://github.com/ydb-platform/ydb/issues/21220
- [x] https://github.com/ydb-platform/ydb/issues/25980
- [ ] https://github.com/ydb-platform/ydb/issues/21222
- [ ] https://github.com/ydb-platform/ydb/issues/21223
- [ ] Add nodes graph to cloud monitoring dashboard
- [ ] Add price range to cloud YDBOPS-12810
- [ ] Add operation log to cloud

#### Only internal installations
- [ ] https://github.com/ydb-platform/ydb/issues/21224
- [ ] https://github.com/ydb-platform/ydb/issues/21225
