### ISSUE TITLE
👑 SQL for database configuration

### ISSUE THREAD

**Issue by Enjection** [ydb-platform/ydb#11462]
## Description

Let database administrators change particular config parts through SQL interface.

## Steps

- [ ] design SQL interface
- [ ] design integration with regular configuration
- [ ] add SQL interface
- [ ] write docs
