### ISSUE TITLE
👑 Incremental Backups to Object Storage

### ISSUE THREAD

**Issue by Enjection** [ydb-platform/ydb#11555]
## Description

Add intra-cluster incremental backups possibility and all infrastructure needed for further backup development as coherent feature.

Internal [design doc](https://github.com/ydb-platform/ydb-rfc/blob/main/0101_advanced-backups-rfc.md).

### Prerequisites

- [ ] #11457

### Main steps

- [ ] Add `object storage` backend to backup collections
- [ ] Implement direct continuous backup to object storage
- [ ] Implement direct restore for incremental backups from object storage
- [ ] Design SQL for backup collection inspection
- [ ] Implement SQL for backup collection inspection
