### ISSUE TITLE
EPIC: disk cleanup

### ISSUE THREAD

**Issue by the-ancient-1** [ydb-platform/ydb#12483]
RFC: https://github.com/ydb-platform/ydb-rfc/blob/main/154_blobstorage_shred.md

Internal ticket - KIKIMR-22161

- [ ] Write an RFC on blobstorage shred
- [ ] Discuss the RFC
- [ ] Implement (TODO: write a detailed plan here)
