### ISSUE TITLE
EPIC: Safe throttling for Out of Space, log overflow, small blob overflow at VDisk

### ISSUE THREAD

**Issue by the-ancient-1** [ydb-platform/ydb#12510]
**В рамках релиза 25-3 -- включение фиче-флага** 

### Documentation

Ответственный: (...)

### Changelog entry

(...)

### Test plan

(...)

### Feature flag

(...)

### Enabled on clusters

(ссылка на YDBOPS-тикет)

## Description

Safely and predictably handle Out of Space situations, log overflow, and accumulation of excessive amounts of small blobs in the index.

VDisks under load should not enter a state where nothing can be done without involving the operations team armed with dstool. A tablet on a full disk should maintain the ability to delete data.

Work Plan (starting December 5)
2d - December 9

- [x] Learn to generate load that creates problematic situations (compaction in circles, many small blobs)

5d - December 16

- [x] #12515

3d - December 19

- [x] #12651

3d - December 24

- [x] #12820

2d - December 26

- [x] #13084

4d - January 10

- [x] Write documentation about configuration

2d - January 14

- [ ] Ensure alert appears for on-duty engineer / show NBS what to monitor

3d - January 17

- [x] #13267

3d - January 22

- [x] Create graphs, settings, logs about the log

4d - January 27

- [x] Write configuration documentation

3d - January 30

- [x] #13083

3d - February 4

- [x] Create graphs, settings, logs about out of space

4d - February 10

- [x] Write documentation about configuration

43d

**Definition of Done:**

1. A cluster user can fill up the cluster's disk space using only their application and independently resolve this situation by deleting data.
2. A cluster user can fill up the cluster with small blobs using only their application and will receive alerts and appropriate throttling.

**Comment by the-ancient-1** [comment]
Ниже - черновик.
Первая подзадача:
- [ ] запись большого количества мелких блобов (и вообще отставание компакшн) должна приводить к троттлингу записи мелких блобов, то что происходит троттлинг должно быть явно видно по графикам, веб интерфейсу и логам
- [ ] наличие слишком большого количества мелких блобов должно приводить к срабатыванию алерта еще до троттлинга

При превышении пороговых количеств гигабайт, используемых для хранения мелких (inplaced)блобов (или чанков индекса?), необходимы:
- [ ] графики - текущее значение и пороговые
- [ ] ворнинг
- [ ] алерт
- [ ] плавное замедление записи новых мелких блобов, вплоть до полной остановки, можно ограничивать скорость градиентом от честной доли модельной скорости устройства до 0 между парой точек "заполненности".
- [ ] для всего этого настройки порогов и выключатели через ICB + CMS

- [ ] нужен RFC описывающий как и для чего будет замедляться и останавливаться работа, на какие алерты можно будет смотреть, чтобы мы этот RFC показали ребятам NBS заранее и они меньше удивились когда у них загорятся алерты, все замедлится и остановится.

- [ ] альтернативный / дополнительный путь реализации - троттлинг входящей нагрузки на запись в лог, происходящий в условиях, когда компакшн высоких уровней не успевает и копится слишком много чанков полученных в результате компакшна фреша.

Вторая подзадача:
- [ ] переполнение лога должно приводить к алерту еще до троттлинга
- [ ] переполнение лога должно приводить к троттлингу нагрузки на VDisk вплоть до полной остановки

Третья подзадача 
- [ ] Приближение к Out of Space  должно приводить к троттлингу записи
- [ ] Пожелтение групп не должно мешать поднятию таблеток и удалению данных, возможно для этого удаление потребуется дополнительно разметить (?)
