### ISSUE TITLE
Meta-ticket for all errors in JSON plan representations and pretty-table format

### ISSUE THREAD

**Issue by pavelvelikhov** [ydb-platform/ydb#1797]
There are multiple minor problems with plan representations:

- [ ] TPCDS queries: 16, 92, 94, 95, 96 all have an invalid empty simplified plan in JSON: https://github.com/ydb-platform/ydb/issues/1793
- [ ] TPCDS queries: 61, 88, 90 have a wrong number of join inputs: https://github.com/ydb-platform/ydb/issues/1794
- [ ] TPCH query Q16: Missing details of Aggregate operator: https://github.com/ydb-platform/ydb/issues/1795
- [ ] All analyze plans: stats for the execution stage are copied: https://github.com/ydb-platform/ydb/issues/1796
