### ISSUE TITLE
Auto complete in YDB CLI commands (in interactive mode)

### ISSUE THREAD

**Issue by vityaman** [ydb-platform/ydb#9056]
We already added `YQL` highlighting to `YDB CLI` at MR #7448. It would be nice to have autosuggestions like we have in the Web UI editor powered by [websql-autocomplete](https://github.com/gravity-ui/websql-autocomplete).

**Comment by vityaman** [comment]
Autocomplete library for ANTLR4 based languages called `antlr4c3` [was released](https://github.com/mike-lischke/antlr4-c3/issues/155) with tag `cpp-2.0.0` and will be added to [contrib/libs](https://github.com/ydb-platform/ydb/tree/main/contrib/libs) soon.

**Comment by vityaman** [comment]
# Автодополнение YQL

## Продукты

### (Done) Автодополнение в Web UI

Технологии: `Web, TypeScript`.

Уже реализовано на `WebSQL Autocomplete`, поддерживается много разных диалектов SQL.

### (ToDo) Автодополнение в YDB CLI

Технологии: `Native, C++20`.

Не реализовано.

### (Wish) Языковой сервер

Технологии: `Native`.

Можно упаковать `NodeJS` с кодом и поставлять отдельным приложением, с которым по RPC будут общаться IDE плагины. Так мы будем переиспользовать `WebSQL`.

В теории можно упаковать и в `CLI` как-то, но тогда бинарь будет тяжеловесным.

Упростит реализацию плагинов для нескольких IDE сразу.

### (Wish) Плагин для VSCode

Технологии: `Node JS, TypeScript`.

Вероятно, можно просто переиспользовать `WebSQL Autocomplete` для реализации плагина.

Можно реализовать `LSP` и написать плагин-обертку над RPC.

### (Wish) Плагин для IDEA

Технологии: `JVM, Java, Kotlin`.

Можно написать полностью на `Java` или `Kotlin`.

Можно реализовать `LSP` и написать плагин-обертку над RPC.

## Варианты реализации

### (Risk: High) Линковка YDB CLI с WASM рантаймом для вызова WebSQL

(Плохо) Не очевидно, как делать. Разбухает бинарь.

### (Risk: High) Компилирование WASM в нативный код для вызова WebSQL

(Плохо) Не очевидно, как делать. Разбухает бинарь.

### (Risk: Medium) Переписывание WebSQL на кроссплатформенный язык целиком

Нужно договориться с командой поддержки WebSQL, чтобы они далее это поддерживали и интегрировали в Web UI.

(Хорошо) Может быть реализовано одним человеком (@vityaman) при помощи LLM.

(Хорошо) Избавляемся от необходимости поддерживать два сложных проекта с одинаковой функциональностью.

Желательно наличие ANTLR4 рантайма, но в теории можно специлизировать: под Web используем antlr4ng, а C++ слинкуем с соответсвующим рантаймом antlr4, но это запарно.

### (Risk: Medium) Реализация независимого движка подсказок в YDB CLI и YQL

(Плохо) Придется поддерживать 2 сложных проекта независимо.

(Плохо) Код на C++ сложно поддерживать.

(Плохо) Придется синхронизировать фичи c WebSQL.

### (Risk: Low) Переписывание YQL части WebSQL c TypeScript на С++

(Хорошо) Может быть реализовано одним человеком (@vityaman) при помощи LLM.

(Хорошо) Можно занять исполнителя другими задачами: улучщение WebSQL.

(Плохо) Будем жить как в ANTLR, будем периодически выполнять рутинную работу по переписыванию изменений в WebSQL на С++.

**Comment by vityaman** [comment]
TODO (29 Jan 2025)

- [ ] Explore how to provide suggestions in CLI without printing a new line (like in Python 3 CLI).

- [ ] Explore performance problems in VSCode terminal (ZSH).

- [ ] Refactor the MR [#12386](https://github.com/ydb-platform/ydb/pull/12386) to separate core autocomplete from the `Replxx` API.

**Comment by vityaman** [comment]
- USE is only for YT, flag that USE is supported (https://github.com/ytsaurus/ytsaurus/commit/58e7058b41b954086b7e5ce376491002b7ff4020).
- Completer features must be configurable.
- Functions: Aggregating (not where), Window (not where, group by), Standard.

- [ ] Finish Regex Lexer.
- [ ] Investigate C3 parser call stacks for tokens.
- [ ] Design `NameSource` (use `Futures`, prefix filtration, output limit, no paging).
- [ ] Parse parser call stacks weights.

**Comment by vityaman** [comment]
## Agenda

- [ ] `sql/v1/highlight`: https://github.com/ytsaurus/ytsaurus/pull/1127 is ready and contains `ELexerFlavor`.
- [ ] `sql/v1/complete`: https://github.com/ytsaurus/ytsaurus/pull/1144 needs `ELexerFlavor`.
- [ ] `sql/v1/complete`: https://github.com/mike-lischke/antlr4-c3/issues/171 created.
- [ ] `sql/v1/complete`: roadmap, task decomposition
- [ ] `sql/v1/complete`: need a `YQL-XXXXX` ticket or an issue at `ytsaurus` for a complete epic, maybe subtickets for other tasks.
- [ ] `sql/v1/complete`: Name Service Design (?)

## Result

- [ ] TODO

## Pictures

![Image](https://github.com/user-attachments/assets/32b9956e-4637-45de-80ec-a331ab294053)

**Comment by vityaman** [comment]
-[ ] TODO: Suggest token sequences even with punctuation, but without lonely punctuatiion. For example, suggest `Optional <`, but not `<`.

**Comment by vityaman** [comment]
![Image](https://github.com/user-attachments/assets/433775e9-814e-45fc-9763-e63678916020)

**Comment by vityaman** [comment]
## Agenda

- [ ] https://github.com/ytsaurus/ytsaurus/pull/1127
- [ ] https://github.com/ytsaurus/ytsaurus/pull/1144
- [ ] https://github.com/ytsaurus/ytsaurus/pull/1151
- [ ] Will add a token sequences support (`GROUP BY`, `Optional <`)
- [ ] Can add ranking for types and functions after then
- [ ] Design perspectives of `sql/v1/complete`

## Result

-

**Comment by vityaman** [comment]
Plan
- [ ] Refactor `sql/v1/complete` architecture and then support function completion.
- [ ] Get functions and types frequencies from the `rules_corr_basic.json` and introduce ranking.
- [ ] Introduce token sequences completions and complex types camel-case.

**Comment by vityaman** [comment]
Token sequences plan
- [ ] [Easy] Support `GROUP BY`, `ORDER BY`.
- [ ] [Easy] Support `Optional`, `List<`, `Dict<`.

**Comment by vityaman** [comment]
TODO: Suggest types at function args.

**Comment by vityaman** [comment]
Agenda
- [ ] Token ranking should parse stack dependent as tokens mean different in different contexts.

**Comment by vityaman** [comment]
Thoughts explored while the development of tables suggestions.

1. Schema interface static implementation should be tested. But it is required for unit tests.
2. !!! `antlr4-c3` wrapper and `CompletionEngine` should be altered to support completion with a cursor, not just cut prefix. `SplitQueryToStatements` usage should be adopted.
3. Some hack is required at `Replxx` to insert closing ``` ` ``` and append ``` ` ``` to all candidates.
4. !!! Compute `TCompletedToken` fairly.
5. Split module `name` into `name/schema`, `name/service`.
6. `TNameResponse` should contains `TListResponse::NameHintLength`.
7. `Futures` should be handled properly.
8. `Schema` would be used while semantic analysis.
9. Need to rewrite unit tests to use api with `#` as a cursor position.
10. !!! Split `NameService` into smaller parts and use `UnionNameService`.

**Comment by vityaman** [comment]
Agenda
- PR: with `sql/v1/highlight`
- Proposal: `sql/v1/complete` observability
- Bug: `PRAGMA` completion

```json
[
  { "name": "Keyword", "pattern": {
    "body": "select|insert|...",
    "is-case-insensitive": true
  }},
  { "name": "Function", "pattern": {
    "body": "<...>::<...>"
  }},
  { "name": "Function", "pattern": {
    "body": "<...>("
  }},
  ...
]
```

**Comment by vityaman** [comment]
UI: Text, Icon, Label

**Comment by vityaman** [comment]
This is how autocomplete is tested in the ClickHouse CLI.
https://github.com/ClickHouse/ClickHouse/blob/a1b36e3be098c07c6d410b61e9a4fbcdc5b3bc5a/tests/queries/0_stateless/01676_clickhouse_client_autocomplete.python
